name: Release

env:
    CI: 'true'

on:
    push:
        branches:
            - main
            - next
            - next-major
            - beta
            - alpha
            - '[0-9]+.x' # N.x
            - '[0-9]+.x.x' # N.x.x
            - '[0-9]+.[0-9]+.x' # N.N.x

jobs:
    npm-publish:
        name: npm publish

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install
              uses: bahmutov/npm-install@v1

            - name: Build
              run: npm run build

            - name: Semantic Release
              if: success()
              env:
                  GIT_AUTHOR_NAME: Whitebox Bot
                  GIT_AUTHOR_EMAIL: whitebox-bot@whitebox.com
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
              run: npm run semantic-release
